esphome:
  libraries:
    - SPI
    - lsatan/SmartRC-CC1101-Driver-Lib

external_components:
  - source:
      type: git
      url: https://github.com/AeroXuk/esphome_cc1101.git
    components: [ cc1101 ]
    refresh: 1min

logger:
  level: VERBOSE

cc1101:
  id: cc1101_chip
  clk_pin: GPIO18
  mosi_pin: GPIO19
  miso_pin: GPIO16
  cs_pin: GPIO17
  gdo0_pin: GPIO20
  gdo2_pin: GPIO21
  frequency: 868.35
